name: Deploy
# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Name of the job
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy
      # appleboy/ssh-action is an action from marketplace, v0.1.4 is its version number
      # https://github.com/marketplace/actions/ssh-remote-commands
        uses: appleboy/ssh-action@v0.1.4 #
        with:
          host: ${{secrets.DevOps_HOST}}
          key: ${{secrets.DevOps_SSH_PRIVATE_KEY}}
          username: ${{secrets.DevOps_USER}}
          script: |
            cd DevOpsBootcamp;git pull
            echo 'Deployment successful to the server'